[package]
name = "qvd_utils"
version = "0.1.0"
authors = ["Sam Bentley <sbentley@ruffer.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
chrono = "0.4.19"
quick-xml = { version = "0.20.0", features = ["serialize"]}